### ISSUE TITLE
Please select a device

### ISSUE THREAD

**Issue by wakeatnight** [git-moss/Push4Bitwig#179] opened 2015-10-10 23:29 UTC
I am having a problem, where sometimes when I switch tracks on the Push it says "Please select a device". When Iook into it, there is infact no device selected. Wouldn't it make sense to select the first device, if no other is selected otherwise. I am running Bitwig 1.2 on Ubuntu 15.04.

I would like to offer more cases when it happens but I can't find a pattern (when it starts "unselecting" devices). What I can say, is that it happens with every project and I can see it multiple times per hour.

Is there a way to fix this?

**Comment by git-moss** [comment] 2015-10-11 11:09
Same as #56.
I cannot reproduce that, also tried the Sampler problem Mike described.
A current Bug is that Devices on Group tracks are not sent which will be fixed in the next Bitwig version.

**Closed by git-moss** 2015-10-11 11:09 UTC

**Comment by wakeatnight** [comment] 2015-10-11 13:56
I posted because on #56 I used Bitwig 1.1.8. Now I updated to 1.2 and it still occurs. I hoped the new 1.2 Devices features will solve that but sadly, no. Performing is very inconvenient if I have to use the mouse to select an Instrument Layer containing my Macros. If there is any setting that you have set that might do the trick, please let me know.
